# Generated by Django 3.2 on 2021-08-25 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ceuApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lname',
            new_name='last_name',
        ),
    ]
