# Generated by Django 2.2 on 2021-08-25 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ceuApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('courses_ord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_with_users', to='ceuApp.Course')),
                ('users_ord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_added_courses', to='ceuApp.User')),
            ],
        ),
    ]
