# Generated by Django 2.2 on 2021-08-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceuApp', '0003_auto_20210826_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.IntegerField(default=100),
        ),
    ]
