# Generated by Django 3.2 on 2021-08-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceuApp', '0004_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.TextField()),
                ('street2', models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField(max_length=2)),
                ('zip', models.IntegerField(max_length=5)),
            ],
        ),
    ]
