# Generated by Django 3.2 on 2021-08-25 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ceuApp', '0005_billing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billing',
            old_name='zip',
            new_name='zipcode',
        ),
    ]
