# Generated by Django 3.2 on 2021-08-25 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ceuApp', '0006_rename_zip_billing_zipcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Billing',
        ),
    ]
